### ISSUE TITLE
android-reference-app error

### ISSUE THREAD

**Issue by noobiewoobie** [AgoraIO/video-sdk-samples-android#15]
I don't understand why none of these video sdk providers , have any working sample to make the functionality understand. Literally, this is my third library and this also doesn't work. I guess it doesn't matter for the companies to make it easy for the developers. Most irritating thing is you cannot even get help directly for these issues. I mean seriously, raise a ticket and that page doesn't even include this option. Instead of wasting hours and days on the internet looking for a fix I would rather move onto some other sdk. I have to work on my own app that's already enough for me, so why would I waste time on fixing your sdk issues. Seriously, fix your samples. Trying to load the android reference app in android studio fails with the following error:-

`Null extracted folder for artifact: ResolvedArtifact(componentIdentifier=AgoraScreenShareExtension.aar, variant=local file, variantName=null, artifactFile=D:\SourceCodes\Classes\agora\video-sdk-samples-android\product-workflow\libs\AgoraScreenShareExtension.aar, isTestFixturesArtifact=false, extractedFolder=null, publishedLintJar=null, dependencyType=ANDROID, isWrappedModule=false, buildMapping={__current_build__=D:\SourceCodes\Classes\agora\video-sdk-samples-android\android-reference-app})`
![agora_error](https://github.com/AgoraIO/video-sdk-samples-android/assets/104965090/35f5ca81-bcd7-46e4-a815-e48c3c111302)

**Comment by hanzotruongdev** [comment]
I faced the same Issue!

**Comment by noobiewoobie** [comment]
> I faced the same Issue!

The samples provided on github don't work. I had to contact agora via their dashboard to get working samples

**Comment by saudsami** [comment]
You need to put the `AgoraScreenShareExtension.aar file` from the downloaded SDK package in the `video-sdk-samples-android\product-workflow\libs` folder.
This step is described [here](https://docs.agora.io/en/video-calling/develop/product-workflow?platform=android#prerequisites).

**Comment by saudsami** [comment]
Added the `AgoraScreenShareExtension.aar` file to the repo so that the project runs out of the box without any changes.
