### ISSUE TITLE
Issue with Agora ScreenShare on Android 

### ISSUE THREAD

**Issue by softsan** [AgoraIO/video-sdk-samples-android#6]
I am following [this](https://docs.agora.io/en/video-calling/develop/product-workflow?platform=android) guidelines to use Screen sharing with my android project. but I am getting this runtime error while starting a screen sharing:

```
W/System.err: java.lang.NoSuchMethodError: no non-static method "Lio/agora/rtc2/extensions/MediaProjectionSource$ScreenCaptureParameters;.<init>(IIIZ)V"
E/rtc: #
    # Fatal error in: ../../../../../media_sdk_script/media_engine2/webrtc/sdk/android/src/jni/jni_generator_helper.cc, line 59
    # last system error: 2
    # Check failed: !env->ExceptionCheck()
    # error during GetMethodID: <init>, (IIIZ)V
```

**Comment by PodolianBohdan** [comment]
same, @softsan do you fix that?

**Comment by saudsami** [comment]
The screen-sharing guide has been updated and the extension is added to the repository.
